### ISSUE TITLE
nile init: Greenlet error using python3.10

### ISSUE THREAD

**Issue by samlaf** [OpenZeppelin/nile#105]
I have python 3.10 installed with conda (`conda create --name py310 python=3.10; conda activate py310`)
After installing nile and running `nile init`, I get
```
  Running setup.py install for greenlet ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for greenlet did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      running install
      running build
      running build_ext
      building 'greenlet' extension
      creating build
      creating build/temp.linux-x86_64-3.10
      gcc -pthread -B /home/samlaf/anaconda3/envs/py310/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/samlaf/anaconda3/envs/py310/include -fPIC -O2 -isystem /home/samlaf/anaconda3/envs/py310/include -fPIC -I/home/samlaf/devel/starkware/nile-test/env/include -I/home/samlaf/anaconda3/envs/py310/include/python3.10 -c greenlet.c -o build/temp.linux-x86_64-3.10/greenlet.o
      greenlet.c: In function ‘g_calltrace’:
      greenlet.c:566:10: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘use_tracing’; did you mean ‘tracing’?
        566 |  tstate->use_tracing = 0;
            |          ^~~~~~~~~~~
            |          tracing
      greenlet.c:569:10: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘use_tracing’; did you mean ‘tracing’?
        569 |  tstate->use_tracing = (tstate->tracing <= 0 &&
            |          ^~~~~~~~~~~
            |          tracing
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> greenlet

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
Traceback (most recent call last):
  File "/home/samlaf/devel/starkware/nile-test/env/bin/nile", line 8, in <module>
    sys.exit(cli())
  File "/home/samlaf/devel/starkware/nile-test/env/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/samlaf/devel/starkware/nile-test/env/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/samlaf/devel/starkware/nile-test/env/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/samlaf/devel/starkware/nile-test/env/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/samlaf/devel/starkware/nile-test/env/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/samlaf/devel/starkware/nile-test/env/lib/python3.10/site-packages/nile/cli.py", line 61, in init
    init_command()
  File "/home/samlaf/devel/starkware/nile-test/env/lib/python3.10/site-packages/nile/core/init.py", line 19, in init
    install()
  File "/home/samlaf/devel/starkware/nile-test/env/lib/python3.10/site-packages/nile/core/install.py", line 10, in install
    subprocess.check_call(
  File "/home/samlaf/anaconda3/envs/py310/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/samlaf/devel/starkware/nile-test/env/bin/python3', '-m', 'pip', 'install', 'cairo-lang', 'starknet-devnet']' returned non-zero exit status 1.
```

**Comment by andrew-fleming** [comment]
Hey @samlaf, thanks for bringing this up! I believe this is a dependency issue with cairo-lang. I can recommend two approaches. Either:
1. `pip install greenlet==1.1.2`
    - you might need to also fix [the Collections issue](https://github.com/starkware-libs/cairo-lang/issues/38) in your venv. Go to `env/lib/python3.10/site-packages/frozendict/__init__.py` and change the first import to `import collections.abc as collections`
2. Or switch to Python3.7 - 3.9 until dependencies are fixed

**Comment by samlaf** [comment]
When I use python 3.9, I get a maximum recursion reached error:
```
> nile compile                                                                               (py310) 
📁 Creating artifacts/abis to store compilation artifacts
🤖 Compiling all Cairo contracts in the contracts directory
🔨 Compiling contracts/contract.cairo
Traceback (most recent call last):
  File "/home/samlaf/devel/starkware/cairo_venv/bin/starknet-compile", line 10, in <module>
    sys.exit(main())
  File "/home/samlaf/devel/starkware/cairo_venv/lib/python3.9/site-packages/starkware/starknet/compiler/compile.py", line 189, in main
    preprocessed = cairo_compile_common(
  File "/home/samlaf/devel/starkware/cairo_venv/lib/python3.9/site-packages/starkware/cairo/lang/compiler/cairo_compile.py", line 134, in cairo_compile_common
    assembled_program.Schema().dump(assembled_program), out, indent=4, sort_keys=True
  File "/home/samlaf/devel/starkware/cairo_venv/lib/python3.9/site-packages/marshmallow_dataclass/lazy_class_attribute.py", line 33, in __get__
    setattr(cls, self.name, self.func())
  File "/home/samlaf/devel/starkware/cairo_venv/lib/python3.9/site-packages/marshmallow_dataclass/__init__.py", line 350, in class_schema
    return _internal_class_schema(clazz, base_schema, clazz_frame)
  File "/home/samlaf/devel/starkware/cairo_venv/lib/python3.9/site-packages/marshmallow_dataclass/__init__.py", line 393, in _internal_class_schema
    attributes.update(
  File "/home/samlaf/devel/starkware/cairo_venv/lib/python3.9/site-packages/marshmallow_dataclass/__init__.py", line 396, in <genexpr>
    field_for_schema(
  File "/home/samlaf/devel/starkware/cairo_venv/lib/python3.9/site-packages/marshmallow_dataclass/__init__.py", line 711, in field_for_schema
    nested_schema = getattr(typ, "Schema", None)
  File "/home/samlaf/devel/starkware/cairo_venv/lib/python3.9/site-packages/marshmallow_dataclass/lazy_class_attribute.py", line 33, in __get__
    setattr(cls, self.name, self.func())
  File "/home/samlaf/devel/starkware/cairo_venv/lib/python3.9/site-packages/marshmallow_dataclass/__init__.py", line 350, in class_schema
    return _internal_class_schema(clazz, base_schema, clazz_frame)
  File "/home/samlaf/devel/starkware/cairo_venv/lib/python3.9/site-packages/marshmallow_dataclass/__init__.py", line 393, in _internal_class_schema
    attributes.update(
  File "/home/samlaf/devel/starkware/cairo_venv/lib/python3.9/site-packages/marshmallow_dataclass/__init__.py", line 396, in <genexpr>
    field_for_schema(
  File "/home/samlaf/devel/starkware/cairo_venv/lib/python3.9/site-packages/marshmallow_dataclass/__init__.py", line 686, in field_for_schema
    generic_field = _field_for_generic_type(typ, base_schema, typ_frame, **metadata)
  File "/home/samlaf/devel/starkware/cairo_venv/lib/python3.9/site-packages/marshmallow_dataclass/__init__.py", line 559, in _field_for_generic_type
    return field_for_schema(
...
  File "/home/samlaf/devel/starkware/cairo_venv/lib/python3.9/site-packages/marshmallow_dataclass/__init__.py", line 396, in <genexpr>
    field_for_schema(
  File "/home/samlaf/devel/starkware/cairo_venv/lib/python3.9/site-packages/marshmallow_dataclass/__init__.py", line 686, in field_for_schema
    generic_field = _field_for_generic_type(typ, base_schema, typ_frame, **metadata)
  File "/home/samlaf/devel/starkware/cairo_venv/lib/python3.9/site-packages/marshmallow_dataclass/__init__.py", line 559, in _field_for_generic_type
    return field_for_schema(
  File "/home/samlaf/devel/starkware/cairo_venv/lib/python3.9/site-packages/marshmallow_dataclass/__init__.py", line 686, in field_for_schema
    generic_field = _field_for_generic_type(typ, base_schema, typ_frame, **metadata)
  File "/home/samlaf/devel/starkware/cairo_venv/lib/python3.9/site-packages/marshmallow_dataclass/__init__.py", line 528, in _field_for_generic_type
    children = tuple(
  File "/home/samlaf/devel/starkware/cairo_venv/lib/python3.9/site-packages/marshmallow_dataclass/__init__.py", line 529, in <genexpr>
    field_for_schema(arg, base_schema=base_schema, typ_frame=typ_frame)
  File "/home/samlaf/devel/starkware/cairo_venv/lib/python3.9/site-packages/marshmallow_dataclass/__init__.py", line 718, in field_for_schema
    or _internal_class_schema(typ, base_schema, typ_frame)
  File "/home/samlaf/devel/starkware/cairo_venv/lib/python3.9/site-packages/marshmallow_dataclass/__init__.py", line 393, in _internal_class_schema
    attributes.update(
  File "/home/samlaf/devel/starkware/cairo_venv/lib/python3.9/site-packages/marshmallow_dataclass/__init__.py", line 396, in <genexpr>
    field_for_schema(
  File "/home/samlaf/devel/starkware/cairo_venv/lib/python3.9/site-packages/marshmallow_dataclass/__init__.py", line 686, in field_for_schema
    generic_field = _field_for_generic_type(typ, base_schema, typ_frame, **metadata)
  File "/home/samlaf/devel/starkware/cairo_venv/lib/python3.9/site-packages/marshmallow_dataclass/__init__.py", line 559, in _field_for_generic_type
    return field_for_schema(
  File "/home/samlaf/devel/starkware/cairo_venv/lib/python3.9/site-packages/marshmallow_dataclass/__init__.py", line 686, in field_for_schema
    generic_field = _field_for_generic_type(typ, base_schema, typ_frame, **metadata)
  File "/home/samlaf/devel/starkware/cairo_venv/lib/python3.9/site-packages/marshmallow_dataclass/__init__.py", line 528, in _field_for_generic_type
    children = tuple(
  File "/home/samlaf/devel/starkware/cairo_venv/lib/python3.9/site-packages/marshmallow_dataclass/__init__.py", line 529, in <genexpr>
    field_for_schema(arg, base_schema=base_schema, typ_frame=typ_frame)
  File "/home/samlaf/devel/starkware/cairo_venv/lib/python3.9/site-packages/marshmallow_dataclass/__init__.py", line 718, in field_for_schema
    or _internal_class_schema(typ, base_schema, typ_frame)
  File "/home/samlaf/devel/starkware/cairo_venv/lib/python3.9/site-packages/marshmallow_dataclass/__init__.py", line 385, in _internal_class_schema
    for k, v in inspect.getmembers(clazz)
  File "/home/samlaf/anaconda3/envs/py39/lib/python3.9/inspect.py", line 335, in getmembers
    names = dir(object)
RecursionError: maximum recursion depth exceeded while calling a Python object
🛑 Failed to compile the following 1 contract:
   contracts/contract.cairo
```

**Comment by samlaf** [comment]
I installed `greenlet==1.1.2` and still have the same error.
I also can't find any `frozendict` directory, neither in lib nor lib64.

**Comment by andrew-fleming** [comment]
Ah `marshmallow_dataclass` had a new release the other day which is where the maximum recursion error is coming from 😅 we have to use their previous version for now. Try `pip install marshmallow-dataclass==8.5.3` for Python3.9.

> I also can't find any frozendict directory, neither in lib nor lib64.

Hmm I'll try and recreate this to figure out what's happening.

**Comment by martriay** [comment]
@samlaf any news?

**Comment by EVLRBT-01** [comment]
The following worked for me using 3.10, thanks!
>     1. `pip install greenlet==1.1.2`
>        
>        * you might need to also fix [the Collections issue](https://github.com/starkware-libs/cairo-lang/issues/38) in your venv. Go to `env/lib/python3.10/site-packages/frozendict/__init__.py` and change the first import to `import collections.abc as collections`

**Comment by samlaf** [comment]
Thanks @EVLRBT-01!
I was using nile for a hackathon, and haven't had time to get back to it since. I will try to this week though, just to confirm that its working now.

**Comment by koloz193** [comment]
you can also use this as a workaround for testing https://github.com/OpenZeppelin/cairo-contracts/pull/299

**Comment by ishitarastogi** [comment]
I have python 3.10 and after running nile init, I get
```
 Running setup.py install for greenlet ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for greenlet did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      running install
      /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      building 'greenlet' extension
      creating build
      creating build/temp.macosx-10.9-universal2-cpython-310
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c greenlet.c -o build/temp.macosx-10.9-universal2-cpython-310/greenlet.o
      In file included from greenlet.c:359:
      In file included from ./slp_platformselect.h:47:
      ./platform/switch_aarch64_gcc.h:62:51: warning: value size does not match register size specified by the constraint and modifier [-Wasm-operand-widths]
                 __asm__ volatile ("mov %0, #0" : "=r" (err));
                                                        ^
      ./platform/switch_aarch64_gcc.h:62:35: note: use constraint modifier "w"
                 __asm__ volatile ("mov %0, #0" : "=r" (err));
                                        ^~
                                        %w0
      greenlet.c:566:10: error: no member named 'use_tracing' in 'struct _ts'
              tstate->use_tracing = 0;
              ~~~~~~  ^
      greenlet.c:569:10: error: no member named 'use_tracing' in 'struct _ts'
              tstate->use_tracing = (tstate->tracing <= 0 &&
              ~~~~~~  ^
      1 warning and 2 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> greenlet

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

I have updated the greenlet and fix the collection issues too.

**Comment by ChiHaoLu** [comment]
> I have python 3.10 and after running nile init, I get
> 
> ```
>  Running setup.py install for greenlet ... error
>   error: subprocess-exited-with-error
>   
>   × Running setup.py install for greenlet did not run successfully.
>   │ exit code: 1
>   ╰─> [26 lines of output]
>       running install
>       /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
>         warnings.warn(
>       running build
>       running build_ext
>       building 'greenlet' extension
>       creating build
>       creating build/temp.macosx-10.9-universal2-cpython-310
>       clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c greenlet.c -o build/temp.macosx-10.9-universal2-cpython-310/greenlet.o
>       In file included from greenlet.c:359:
>       In file included from ./slp_platformselect.h:47:
>       ./platform/switch_aarch64_gcc.h:62:51: warning: value size does not match register size specified by the constraint and modifier [-Wasm-operand-widths]
>                  __asm__ volatile ("mov %0, #0" : "=r" (err));
>                                                         ^
>       ./platform/switch_aarch64_gcc.h:62:35: note: use constraint modifier "w"
>                  __asm__ volatile ("mov %0, #0" : "=r" (err));
>                                         ^~
>                                         %w0
>       greenlet.c:566:10: error: no member named 'use_tracing' in 'struct _ts'
>               tstate->use_tracing = 0;
>               ~~~~~~  ^
>       greenlet.c:569:10: error: no member named 'use_tracing' in 'struct _ts'
>               tstate->use_tracing = (tstate->tracing <= 0 &&
>               ~~~~~~  ^
>       1 warning and 2 errors generated.
>       error: command '/usr/bin/clang' failed with exit code 1
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: legacy-install-failure
> 
> × Encountered error while trying to install package.
> ╰─> greenlet
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for output from the failure.
> ```
> 
> I have updated the greenlet and fix the collection issues too.

Same problems here.

**Comment by acollette** [comment]
> 

+1 here

**Comment by martriay** [comment]
Python 3.10 [is not supported](https://github.com/OpenZeppelin/nile/blob/main/setup.cfg#L23), the [cairo language doesn't support it](https://github.com/starkware-libs/cairo-lang/issues/27) either.
