### ISSUE TITLE
Signed transactions not working on goerli (but working on local devnet)

### ISSUE THREAD

**Issue by 0xtonysprocket** [OpenZeppelin/nile#143]
First, nile is awesome

setup of account and deployment of contracts works great on devnet and goerli; signed transactions work great on devnet but the minute I try to send a signed transaction on goerli (nothing changed except passing the network flag) I get the following error from debug:

```
🛑 The transaction was rejected but no contract address was identified in the error message.
Error message:
Error at pc=0:133:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:746)
Unknown location (pc=0:682)
Error message: Account: invalid signature
Unknown location (pc=0:347)
Unknown location (pc=0:321)

Traceback (most recent call last):
  File "<hint14>", line 1, in <module>
  File "/app/src/starkware/starknet/services/batcher/starknet_batcher_venv-site/starkware/cairo/lang/builtins/signature/signature_builtin_runner.py", line 94, in add_signature
    ), f"Signature hint must point to the signature builtin segment, not {addr}."
AssertionError: Signature hint must point to the signature builtin segment, not 14:0.
```

I'm not really sure where to start debugging this, I found the line in starknet repo https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/cairo/lang/builtins/signature/signature_builtin_runner.py#L94

Thanks in advance for your help!

**Comment by 0xtonysprocket** [comment]
```
nile setup {priv key alias} 
```
to create the account

```
def run(nre):
          # send tx
    tx_one = user_account.send(
        to=ERC, method='approve', calldata=approve_args, max_fee=MAX_FEE)
        ```

**Comment by 0xtonysprocket** [comment]
approve args are [spender, amount] where spender is an address and amount is Uint256
