### ISSUE TITLE
Error installing Cairo on Mac M1

### ISSUE THREAD

**Issue by potti** [OpenZeppelin/nile#223]
I got an error when i run `nile init`, and i'm not familiar with python , anyone know how to fix this? 
```
Using legacy 'setup.py install' for varint, since package 'wheel' is not installed.
Installing collected packages: varint, netaddr, mypy-extensions, lru-dict, lark-parser, iniconfig, greenlet, frozendict, bitarray, Werkzeug, websockets, typing-extensions, typeguard, toolz, tomli, PyYAML, pyrsistent, pyparsing, pycryptodome, py, protobuf, prometheus-client, pluggy, pipdeptree, parsimonious, numpy, multidict, meinheld, MarkupSafe, itsdangerous, hexbytes, frozenlist, eth-typing, eth-hash, dill, cachetools, base58, attrs, async-timeout, asgiref, yarl, typing-inspect, packaging, multiaddr, jsonschema, Jinja2, cytoolz, aiosignal, pytest, marshmallow, ipfshttpclient, Flask, eth-utils, aiohttp, rlp, pytest-asyncio, marshmallow-oneofschema, marshmallow-enum, marshmallow-dataclass, flask-cors, eth-keys, eth-abi, eth-rlp, eth-keyfile, eth-account, Web3, cairo-lang, starknet-devnet
  Running setup.py install for varint ... done
  Running setup.py install for lru-dict ... done
  Running setup.py install for greenlet ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for greenlet did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      running install
      /Users/potti/nile-demo/env/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      building 'greenlet' extension
      creating build
      creating build/temp.macosx-10.9-universal2-cpython-310
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/opt/homebrew/opt/gmp/include -I/Users/potti/nile-demo/env/include -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c greenlet.c -o build/temp.macosx-10.9-universal2-cpython-310/greenlet.o
      In file included from greenlet.c:359:
      In file included from ./slp_platformselect.h:47:
      ./platform/switch_aarch64_gcc.h:62:51: warning: value size does not match register size specified by the constraint and modifier [-Wasm-operand-widths]
                 __asm__ volatile ("mov %0, #0" : "=r" (err));
                                                        ^
      ./platform/switch_aarch64_gcc.h:62:35: note: use constraint modifier "w"
                 __asm__ volatile ("mov %0, #0" : "=r" (err));
                                        ^~
                                        %w0
      greenlet.c:566:10: error: no member named 'use_tracing' in 'struct _ts'
              tstate->use_tracing = 0;
              ~~~~~~  ^
      greenlet.c:569:10: error: no member named 'use_tracing' in 'struct _ts'
              tstate->use_tracing = (tstate->tracing <= 0 &&
              ~~~~~~  ^
      1 warning and 2 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> greenlet

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
Traceback (most recent call last):
  File "/Users/potti/nile-demo/env/bin/nile", line 8, in <module>
    sys.exit(cli())
  File "/Users/potti/nile-demo/env/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/potti/nile-demo/env/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/potti/nile-demo/env/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/potti/nile-demo/env/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/potti/nile-demo/env/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/potti/nile-demo/env/lib/python3.10/site-packages/nile/cli.py", line 69, in init
    init_command()
  File "/Users/potti/nile-demo/env/lib/python3.10/site-packages/nile/core/init.py", line 19, in init
    install()
  File "/Users/potti/nile-demo/env/lib/python3.10/site-packages/nile/core/install.py", line 10, in install
    subprocess.check_call(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/potti/nile-demo/env/bin/python3', '-m', 'pip', 'install', 'cairo-lang', 'starknet-devnet']' returned non-zero exit status 1.
```

**Comment by ericnordelo** [comment]
Hi @potti. That's an issue coming from starknet-devnet installation. The current starknet-devnet version only supports python until 3.9, and you are using 3.10.

**Comment by ericnordelo** [comment]
@martriay @andrew-fleming, maybe it is worth adding an entry for this in the documentation? It took time to discover what was happening the first time for me.

This could be solved as part of the dependency management issue [#134](https://github.com/OpenZeppelin/nile/issues/134).

**Comment by potti** [comment]
thank you for replay , i'm newcomer to starknet and not familiar with python,  so you means i should uninstall the python3.10 and use python3.9 to do this, right?

**Comment by ericnordelo** [comment]
You can use pyenv or similar to manage multiple python versions simultaneously.

**Comment by martriay** [comment]
> Hi @potti. That's an issue coming from starknet-devnet installation. The current starknet-devnet version only supports python until 3.9, and you are using 3.10.

it's not devnet but [Cairo itself](https://github.com/starkware-libs/cairo-lang/pull/43). I'm not sure we should be documenting language shortcomings (with or without Nile, you won't be able to use Cairo with python 3.10). I guess we could but where 🤔

**Comment by ericnordelo** [comment]
> but where 🤔

I would add it in the README right after the install step.

We don't have to do it like this, but this is an example from straknet-devnet README that was helpful to me when I reached the same problem before.

<img width="770" alt="Screenshot 2022-10-06 at 20 28 02" src="https://user-images.githubusercontent.com/26070224/194390726-f27aa61c-ecad-4671-b45d-f8215f48164b.png">
