### ISSUE TITLE
Script cannot pass integer argument to plugin

### ISSUE THREAD

**Issue by ericglau** [OpenZeppelin/nile#252]
From a script, when calling a Nile plugin that takes an address parameter, users may want to to directly pass in the address as an integer (for convenience) instead of having to convert it to a string.

However, passing in an integer directly to a Nile plugin causes the following error:
```
Traceback (most recent call last):
  File "/Users/eric/git/nile-plugin-int/env/bin/nile", line 8, in <module>
    sys.exit(cli())
  File "/Users/eric/git/nile-plugin-int/env/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/eric/git/nile-plugin-int/env/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/eric/git/nile-plugin-int/env/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/eric/git/nile-plugin-int/env/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/eric/git/nile-plugin-int/env/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/eric/git/nile-plugin-int/env/lib/python3.9/site-packages/nile/cli.py", line 77, in run
    run_command(path, network)
  File "/Users/eric/git/nile-plugin-int/env/lib/python3.9/site-packages/nile/core/run.py", line 14, in run
    script.run(nre)
  File "tests/resources/scripts/script.py", line 3, in run
    nre.deploy_proxy([1234])
  File "/Users/eric/git/nile-plugin-int/env/lib/python3.9/site-packages/nile/core/plugins.py", line 23, in wrapper
    return func(*args, standalone_mode=False, **kwargs)
  File "/Users/eric/git/nile-plugin-int/env/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/eric/git/nile-plugin-int/env/lib/python3.9/site-packages/click/core.py", line 1054, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/Users/eric/git/nile-plugin-int/env/lib/python3.9/site-packages/click/core.py", line 920, in make_context
    self.parse_args(ctx, args)
  File "/Users/eric/git/nile-plugin-int/env/lib/python3.9/site-packages/click/core.py", line 1375, in parse_args
    opts, args, param_order = parser.parse_args(args=args)
  File "/Users/eric/git/nile-plugin-int/env/lib/python3.9/site-packages/click/parser.py", line 337, in parse_args
    self._process_args_for_options(state)
  File "/Users/eric/git/nile-plugin-int/env/lib/python3.9/site-packages/click/parser.py", line 358, in _process_args_for_options
    arglen = len(arg)
TypeError: object of type 'int' has no len()
```

For a minimum reproducible example, see https://github.com/ericglau/nile-plugin-int where the [plugin takes an `int` argument](https://github.com/ericglau/nile-plugin-int/blob/master/nile_upgrades/deploy_proxy.py) and the [script passes in an integer directly](https://github.com/ericglau/nile-plugin-int/blob/master/tests/resources/scripts/script.py).

The workaround is for the user to wrap the integer as a string before calling the plugin, (and since Click is a command line utility this is not necessarily wrong), but the ability to pass in an integer directly would provide for a better user experience.

**Comment by ericglau** [comment]
This was fixed by https://github.com/OpenZeppelin/nile/pull/273 - the plugin needs to use the `nre` scope separate from a `cli` Click command.
