### ISSUE TITLE
Issue trying to use goerli2 in commands

### ISSUE THREAD

**Issue by ericnordelo** [OpenZeppelin/nile#297]
**Running**

`nile setup account --network goerli2`

**Receiving error:**

```
🚀 Deploying Account
Traceback (most recent call last):
  File "/Users/ericnordelo/Documents/OpenSource/OpenZeppelin/nile/env/bin/nile", line 8, in <module>
    sys.exit(cli())
  File "/Users/ericnordelo/Documents/OpenSource/OpenZeppelin/nile/env/lib/python3.9/site-packages/asyncclick/core.py", line 1157, in __call__
    return anyio.run(self._main, main, args, kwargs, **opts)
  File "/Users/ericnordelo/Documents/OpenSource/OpenZeppelin/nile/env/lib/python3.9/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/Users/ericnordelo/Documents/OpenSource/OpenZeppelin/nile/env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/Users/ericnordelo/.pyenv/versions/3.9.1/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/ericnordelo/.pyenv/versions/3.9.1/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/ericnordelo/Documents/OpenSource/OpenZeppelin/nile/env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/Users/ericnordelo/Documents/OpenSource/OpenZeppelin/nile/env/lib/python3.9/site-packages/asyncclick/core.py", line 1160, in _main
    return await main(*args, **kwargs)
  File "/Users/ericnordelo/Documents/OpenSource/OpenZeppelin/nile/env/lib/python3.9/site-packages/asyncclick/core.py", line 1076, in main
    rv = await self.invoke(ctx)
  File "/Users/ericnordelo/Documents/OpenSource/OpenZeppelin/nile/env/lib/python3.9/site-packages/asyncclick/core.py", line 1687, in invoke
    return await _process_result(await sub_ctx.command.invoke(sub_ctx))
  File "/Users/ericnordelo/Documents/OpenSource/OpenZeppelin/nile/env/lib/python3.9/site-packages/asyncclick/core.py", line 1434, in invoke
    return await ctx.invoke(self.callback, **ctx.params)
  File "/Users/ericnordelo/Documents/OpenSource/OpenZeppelin/nile/env/lib/python3.9/site-packages/asyncclick/core.py", line 780, in invoke
    rv = await rv
  File "/Users/ericnordelo/Documents/OpenSource/OpenZeppelin/nile/env/lib/python3.9/site-packages/nile/cli.py", line 152, in setup
    await Account(signer, network, watch_mode=watch_mode)
  File "/Users/ericnordelo/Documents/OpenSource/OpenZeppelin/nile/env/lib/python3.9/site-packages/nile/core/account.py", line 35, in __new__
    await instance.__init__(*a, **kw)
  File "/Users/ericnordelo/Documents/OpenSource/OpenZeppelin/nile/env/lib/python3.9/site-packages/nile/core/account.py", line 81, in __init__
    address, index = await self.deploy(watch_mode=watch_mode)
  File "/Users/ericnordelo/Documents/OpenSource/OpenZeppelin/nile/env/lib/python3.9/site-packages/nile/core/account.py", line 91, in deploy
    address, _ = await deploy(
  File "/Users/ericnordelo/Documents/OpenSource/OpenZeppelin/nile/env/lib/python3.9/site-packages/nile/core/deploy.py", line 29, in deploy
    output = await execute_call(
  File "/Users/ericnordelo/Documents/OpenSource/OpenZeppelin/nile/env/lib/python3.9/site-packages/nile/starknet_cli.py", line 29, in execute_call
    return await capture_stdout(cmd(args=args, command_args=command_args))
  File "/Users/ericnordelo/Documents/OpenSource/OpenZeppelin/nile/env/lib/python3.9/site-packages/nile/starknet_cli.py", line 36, in capture_stdout
    await func
  File "/Users/ericnordelo/Documents/OpenSource/OpenZeppelin/nile/env/lib/python3.9/site-packages/starkware/starknet/cli/starknet_cli.py", line 846, in deploy
    await deploy_tx(args=args)
  File "/Users/ericnordelo/Documents/OpenSource/OpenZeppelin/nile/env/lib/python3.9/site-packages/starkware/starknet/cli/starknet_cli.py", line 884, in deploy_tx
    gateway_client = get_gateway_client(args)
  File "/Users/ericnordelo/Documents/OpenSource/OpenZeppelin/nile/env/lib/python3.9/site-packages/starkware/starknet/cli/starknet_cli.py", line 202, in get_gateway_client
    gateway_url = get_arg_value(
  File "/Users/ericnordelo/Documents/OpenSource/OpenZeppelin/nile/env/lib/python3.9/site-packages/starkware/starknet/cli/starknet_cli.py", line 147, in get_arg_value
    f'{arg_name} must be specified with the "{args.command}" subcommand.\n'
AttributeError: 'types.SimpleNamespace' object has no attribute 'command'
```

**Expected behavior:**

Correct deployment of account.

**How to reproduce:**

Install from main branch with `pip install .`

Run `nile setup account --network goerli2`

**Notes**

This happens also with other commands like `nile deploy a UniversalDeployer --alias udc --ignore_account --network goerli2`

**Comment by ericnordelo** [comment]
This happens when the goerli2 network is not present in the node.json file. I think we should at least add more descriptive feedback for this issue.

**Comment by andrew-fleming** [comment]
With the latest merged changes, this is what's being logging to the console:

```
Got InvalidURL while trying to access /gateway/add_transaction., retrying...
Got InvalidURL while trying to access /gateway/add_transaction., retrying...
Got InvalidURL while trying to access /gateway/add_transaction., retrying...
```

Even with the improved message, I think `get_networks` from common.py should handle this issue better—preferably just resolve the conflict in the function.
