### ISSUE TITLE
Can't invoke functions from deployed contracts

### ISSUE THREAD

**Issue by l-henri** [OpenZeppelin/nile#47]
Hello,
I have deployed a group of contrats on testnet and would like to interact with them using
`nile invoke`
The issue I face is that the goerli.deployments.txt doesn't seem like it is parsed correctly when nile is looking for the ABI:
```
(cairo_venv) macbook-pro-de-henri:starknet-cairo-101 henrilieutaud$ nile invoke 0x001102cdbe07a9b776a30002c331f83f01b7a9154a534fcf1e44a6c213dc9c41 set_teacher_temp 1 1507638031522682312191916131341364110496142099655924630921045603037699363192 --network goerli
usage: starknet [-h] --address ADDRESS --abi ABI --function FUNCTION
                [--inputs [INPUTS [INPUTS ...]]]
                [--signature [SIGNATURE [SIGNATURE ...]]]
starknet: error: argument --abi: can't open 'artifacts/abis/TDERC20.json
': [Errno 2] No such file or directory: 'artifacts/abis/TDERC20.json\n'
```
I have observed this with `nile call` too
Steps to reproduce:
- Deploy more than one contract
- `nile invoke <contract_address> <function_name> <inputs> --network goerli`
Steps to correct:
- Remove all following lines in goerli.deployments.txt

**Comment by martriay** [comment]
Thanks for reporting this! Will take a look

**Comment by martriay** [comment]
Sorry for taking so long. I wasn't able to reproduce this, is this still happening to you? Can you provide more details to reproduce it?

**Comment by threepwave** [comment]
This reproduces for me using the latest (from git) nile on osx w/ python 3.7:
1. Setup environment: 
`python3 -m venv env; source env/bin/activate; git clone https://github.com/OpenZeppelin/nile.git; pip install ./nile; nile init`

2. Compile a contract (including the default contract `contract.cairo`)
`nile compile`

3. Deploy said contract
`nile deploy <contract_name>`

4. Invoke said contract:
`nile invoke 0x01c92c4dbce24ffb53d21c689d64723329c279649f4bbb61c82c84917d354510 set_token_id 5 10`

Results in:
```
usage: starknet [-h] --address ADDRESS --abi ABI --function FUNCTION
                [--inputs [INPUTS [INPUTS ...]]]
                [--signature [SIGNATURE [SIGNATURE ...]]]
starknet: error: argument --abi: can't open 'artifacts/abis/dungeon.json
': [Errno 2] No such file or directory: 'artifacts/abis/dungeon.json\n'
Traceback (most recent call last):
  File "/Users/threepwave/code/cryptsandcaverns/contract/env/bin/nile", line 8, in <module>
    sys.exit(cli())
  File "/Users/threepwave/code/cryptsandcaverns/contract/env/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/threepwave/code/cryptsandcaverns/contract/env/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/threepwave/code/cryptsandcaverns/contract/env/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/threepwave/code/cryptsandcaverns/contract/env/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/threepwave/code/cryptsandcaverns/contract/env/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/threepwave/code/cryptsandcaverns/contract/env/lib/python3.7/site-packages/nile/main.py", line 84, in invoke
    call_or_invoke_command(contract_name, "invoke", method, params, network)
  File "/Users/threepwave/code/cryptsandcaverns/contract/env/lib/python3.7/site-packages/nile/commands/call.py", line 36, in call_or_invoke_command
    subprocess.check_call(command)
  File "/usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['starknet', 'invoke', '--address', '0x01c92c4dbce24ffb53d21c689d64723329c279649f4bbb61c82c84917d354510', '--abi', 'artifacts/abis/dungeon.json\n', '--function', 'set_token_id', '--gateway_url=http://localhost:5001/', '--inputs', '5', '10']' returned non-zero exit status 2.```

**Comment by martriay** [comment]
Fixed in https://github.com/OpenZeppelin/nile/pull/51
