### ISSUE TITLE
abi argument of call command has extra new line character

### ISSUE THREAD

**Issue by milancermak** [OpenZeppelin/nile#59]
Steps to reproduce the issue in a new project:

```
nile init
nile complie
nile deploy --network goerli contract
nile call --network goerli 0xADDRESS get_balance
```

The `nile call` will fail. Here's a trace of the above:

```sh
Ⓟ starkware ~/projects/tmp/nile-issue  ➭ nile init

// SNIP

✅ Dependencies successfully installed
🗄  Creating project directory tree
⛵️ Nile project ready! Try running:

nile compile

Ⓟ starkware ~/projects/tmp/nile-issue  ➭ nile compile
📁 Creating artifacts/abis to store compilation artifacts
🤖 Compiling all Cairo contracts in the contracts directory
🔨 Compiling contracts/contract.cairo
✅ Done
Ⓟ starkware ~/projects/tmp/nile-issue  ➭ nile deploy --network goerli contract
🚀 Deploying contract
⏳ ️Deployment of contract successfully sent at 0x07893a17fda27426550e59d0ee4235377cac92a4aa172775223f6b6321252dca
🧾 Transaction hash: 0x645d26bc92aa744ce8b1fe6e6f597d28195626f0d1a705210939c27e8506313
📦 Registering 0x07893a17fda27426550e59d0ee4235377cac92a4aa172775223f6b6321252dca in goerli.deployments.txt
Ⓟ starkware ~/projects/tmp/nile-issue  ➭ nile call --network goerli 0x07893a17fda27426550e59d0ee4235377cac92a4aa172775223f6b6321252dca get_balance
usage: starknet [-h] --address ADDRESS --abi ABI --function FUNCTION [--inputs [INPUTS ...]] [--nonce NONCE] [--signature [SIGNATURE ...]] [--block_hash BLOCK_HASH] [--block_number BLOCK_NUMBER]
starknet: error: argument --abi: can't open 'artifacts/abis/contract.json
': [Errno 2] No such file or directory: 'artifacts/abis/contract.json\n'
Traceback (most recent call last):
  File "/Users/m/.pyenv/versions/starkware/bin/nile", line 8, in <module>
    sys.exit(cli())
  File "/Users/m/.pyenv/versions/3.9.6/envs/starkware/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/m/.pyenv/versions/3.9.6/envs/starkware/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/m/.pyenv/versions/3.9.6/envs/starkware/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/m/.pyenv/versions/3.9.6/envs/starkware/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/m/.pyenv/versions/3.9.6/envs/starkware/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/m/.pyenv/versions/3.9.6/envs/starkware/lib/python3.9/site-packages/nile/main.py", line 94, in call
    call_or_invoke_command(contract_name, "call", method, params, network)
  File "/Users/m/.pyenv/versions/3.9.6/envs/starkware/lib/python3.9/site-packages/nile/commands/call.py", line 36, in call_or_invoke_command
    subprocess.check_call(command)
  File "/Users/m/.pyenv/versions/3.9.6/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['starknet', 'call', '--address', '0x07893a17fda27426550e59d0ee4235377cac92a4aa172775223f6b6321252dca', '--abi', 'artifacts/abis/contract.json\n', '--function', 'get_balance']' returned non-zero exit status 2.
```

Notice the extra `\n` in the input to the `--abi` arg.

Reproduced with nile 0.3.0

**Comment by martriay** [comment]
Yes! This is fixed but not yet released sorry!
