### ISSUE TITLE
nile run not available in current deployment but documented

### ISSUE THREAD

**Issue by rzmahmood** [OpenZeppelin/nile#61]
The documentation has `nile run` as an example, but I don't believe the current deployment (0.3.0) has that.

Directly doing `pip install git+https://github.com/OpenZeppelin/nile` worked for me however that has other issues, 

e.g. file:
```python
def run(nre):
    address, abi = nre.deploy("NFTBridge", alias="nftBridge")
    print(abi, address)
```

`nile run scripts/deploy.py`

```bash
Traceback (most recent call last):
  File "/Users/x/cairo_venv/bin/nile", line 8, in <module>
    sys.exit(cli())
  File "/Users/x/cairo_venv/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/x/cairo_venv/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/x/cairo_venv/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/x/cairo_venv/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/x/cairo_venv/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/x/cairo_venv/lib/python3.7/site-packages/nile/cli.py", line 45, in run
    run_command(path, network)
  File "/Users/x/cairo_venv/lib/python3.7/site-packages/nile/core/run.py", line 14, in run
    script.run(nre)
  File "scripts/deploy.py", line 2, in run
    address, abi = nre.deploy("NFTBridge", alias="nftBridge")
  File "/Users/x/cairo_venv/lib/python3.7/site-packages/nile/nre.py", line 22, in deploy
    return deploy(contract, arguments, self.network, alias, overriding_path)
  File "/Users/x/cairo_venv/lib/python3.7/site-packages/nile/core/deploy.py", line 23, in deploy
    if len(arguments) > 0:
TypeError: object of type 'NoneType' has no len()
```
Am I missing something?

Thank you!

**Comment by fracek** [comment]
The first issue is probably because we haven't had a release in a while. /cc @martriay 

To fix the second issue, pass `arguments=[]` to `deploy`. I will open a PR to fix that.

**Comment by martriay** [comment]
Thanks for the nudge. I was delaying it because I wanted to squeeze better account support for scripting but I'm harming the world. Done > perfect so I'll ship it.
