### ISSUE TITLE
nile send failing with "TypeError: expected str, bytes or os.PathLike object, not int"

### ISSUE THREAD

**Issue by martinetlee** [OpenZeppelin/nile#76]
Hello!

Using MacOS with Python 3.8.5, 
nile version 0.4.0

I have exported a environment variable `TEST_PRIV` to `123` and successfully run `nile setup TEST_PRIV` with the following output:
```
$ nile setup TEST_PRIV                     
🚀 Deploying Account
⏳ ️Deployment of Account successfully sent at 0x0636ab47cf615028c92a64e9aa9630d5bc93a335aa0ae174fbce2e3f22773cfc
🧾 Transaction hash: 0x40b2b24dd47c1d86079c9c8ecb1f30d556c6132e1247ef7063a82854f63a3fd
📦 Registering deployment as account-0 in localhost.deployments.txt
(base) 
```

now I wanted to interact with a deployed contract and hence running `nile send`
```
nile send TEST_PRIV token1 mint 0x0636ab47cf615028c92a64e9aa9630d5bc93a335aa0ae174fbce2e3f22773cfc 1000 
```

and I get the following error:

```
Traceback (most recent call last):
  File "/Users/redacted/opt/anaconda3/bin/nile", line 8, in <module>
    sys.exit(cli())
  File "/Users/redacted/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/redacted/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/redacted/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/redacted/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/redacted/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/redacted/opt/anaconda3/lib/python3.8/site-packages/nile/cli.py", line 96, in send
    account.send(contract_name, method, params)
  File "/Users/redacted/opt/anaconda3/lib/python3.8/site-packages/nile/core/account.py", line 62, in send
    call_or_invoke(
  File "/Users/redacted/opt/anaconda3/lib/python3.8/site-packages/nile/core/call_or_invoke.py", line 40, in call_or_invoke
    subprocess.check_call(command)
  File "/Users/redacted/opt/anaconda3/lib/python3.8/subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/Users/redacted/opt/anaconda3/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Users/redacted/opt/anaconda3/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/redacted/opt/anaconda3/lib/python3.8/subprocess.py", line 1637, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
TypeError: expected str, bytes or os.PathLike object, not int
(base) 
```

Could any one provide any pointers on how to fix this please? thank you!

Please also let me know if any other information would be helpful for debugging, happy to provide!

**Comment by maryhu-2020** [comment]
same issue happens here

**Comment by martriay** [comment]
Fixed on https://github.com/OpenZeppelin/nile/pull/77.
