### ISSUE TITLE
Dependency (Frozendict) appears to be broken ?

### ISSUE THREAD

**Issue by Amxx** [OpenZeppelin/nile#89]
When trying to run `nile compile` I'm getting the following error

```
Traceback (most recent call last):
  File "/home/amxx/Work/OZ/cairo-contracts/env/bin/starknet-compile", line 7, in <module>
    from starkware.starknet.compiler.compile import main  # noqa
  File "/home/amxx/Work/OZ/cairo-contracts/env/lib/python3.10/site-packages/starkware/starknet/compiler/compile.py", line 7, in <module>
    from starkware.cairo.lang.compiler.assembler import assemble
  File "/home/amxx/Work/OZ/cairo-contracts/env/lib/python3.10/site-packages/starkware/cairo/lang/compiler/assembler.py", line 3, in <module>
    from starkware.cairo.lang.compiler.debug_info import DebugInfo, HintLocation, InstructionLocation
  File "/home/amxx/Work/OZ/cairo-contracts/env/lib/python3.10/site-packages/starkware/cairo/lang/compiler/debug_info.py", line 11, in <module>
    from starkware.starkware_utils.validated_dataclass import ValidatedMarshmallowDataclass
  File "/home/amxx/Work/OZ/cairo-contracts/env/lib/python3.10/site-packages/starkware/starkware_utils/validated_dataclass.py", line 12, in <module>
    from starkware.starkware_utils.validated_fields import Field
  File "/home/amxx/Work/OZ/cairo-contracts/env/lib/python3.10/site-packages/starkware/starkware_utils/validated_fields.py", line 13, in <module>
    from starkware.starkware_utils.marshmallow_dataclass_fields import (
  File "/home/amxx/Work/OZ/cairo-contracts/env/lib/python3.10/site-packages/starkware/starkware_utils/marshmallow_dataclass_fields.py", line 8, in <module>
    from frozendict import frozendict
  File "/home/amxx/Work/OZ/cairo-contracts/env/lib/python3.10/site-packages/frozendict/__init__.py", line 16, in <module>
    class frozendict(collections.Mapping):
AttributeError: module 'collections' has no attribute 'Mapping'
```

Just opening python and ruining `import frozendict` does the same. Indeed, on my machine, running python 3.10.2, `import collections` does not include `Mapping`. There is however a `Mapping` in `collections.abc`

**Comment by Amxx** [comment]
I did modify `/home/amxx/Work/OZ/cairo-contracts/env/lib/python3.10/site-packages/frozendict/__init__.py` to use `collection.abc.Mapping` instead of `collection.Mapping` and apparently that fixed the issue ...

**Comment by martriay** [comment]
This is a [known issue in `cairo-lang`](https://github.com/starkware-libs/cairo-lang/issues/27)

**Comment by martriay** [comment]
Ugh, thanks for the hack! This is a [known issue in `cairo-lang`](https://github.com/starkware-libs/cairo-lang/issues/27) and I would expect it to be fixed upstream instead of us patching it from Nile, so I'm closing this.
